@echo off
rem Generated by install-ai-models.bat
set "HF_HOME=E:\Git\karaoke-1\backend\models\huggingface"
set "HF_HUB_CACHE=E:\Git\karaoke-1\backend\models\huggingface\hub"
set "KARAOKE_AI_ASR_MODEL=E:\Git\karaoke-1\backend\models\qwen\Qwen3-ASR-0.6B"
set "KARAOKE_AI_ALIGNER_MODEL=E:\Git\karaoke-1\backend\models\qwen\Qwen3-ForcedAligner-0.6B"
set "KARAOKE_AI_ALLOW_FALLBACK=false"
set "MSST_INFERENCE_COMMAND="E:\Git\karaoke-1\backend\engines\msst\.venv\Scripts\python.exe" "E:\Git\karaoke-1\backend\engines\msst\inference.py""
set "MSST_CONFIG=E:\Git\karaoke-1\backend\engines\msst\configs\KimberleyJensen\config_vocals_mel_band_roformer_kj.yaml"
set "MSST_CHECKPOINT=E:\Git\karaoke-1\backend\models\roformer\MelBandRoformer.ckpt"
