export const MUSIC_GENRES = Object.freeze([
  "Alternative",
  "Alternative Rock",
  "Ambient",
  "Amapiano",
  "Americana",
  "Afrobeat",
  "Afropop",
  "Blues",
  "Bossa Nova",
  "Britpop",
  "Chanson",
  "Children's Music",
  "Classical",
  "Country",
  "Dance",
  "Dancehall",
  "Disco",
  "Drum & Bass",
  "Dub",
  "Dubstep",
  "EDM",
  "Electronic",
  "Emo",
  "Folk",
  "Funk",
  "Gospel",
  "Grime",
  "Hard Rock",
  "Hardcore",
  "Heavy Metal",
  "Hip-Hop/Rap",
  "House",
  "Indie",
  "Indie Pop",
  "Indie Rock",
  "Industrial",
  "Jazz",
  "K-Pop",
  "Latin",
  "Lo-Fi",
  "Metal",
  "Metalcore",
  "New Age",
  "New Wave",
  "Opera",
  "Pop",
  "Pop Punk",
  "Pop/Rock",
  "Post-Punk",
  "Progressive Rock",
  "Punk",
  "R&B/Soul",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Rock & Roll",
  "Salsa",
  "Singer/Songwriter",
  "Ska",
  "Soft Rock",
  "Soundtrack",
  "Synthpop",
  "Techno",
  "Trance",
  "Trap",
  "Ukrainian Pop",
  "Ukrainian Rock",
  "World"
]);

export const genreOptions = (current) => [
  { value: "", label: "—" },
  ...[...new Set([current, ...MUSIC_GENRES].filter(Boolean))]
    .sort((left, right) => left.localeCompare(right))
    .map((value) => ({ value, label: value }))
];
