from __future__ import annotations

import argparse
import hashlib
import html.parser
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "backend" / "requirements-lock.in"
OUTPUT = ROOT / "backend" / "requirements-lock.txt"
PYPI_JSON = "https://pypi.org/pypi/{name}/{version}/json"
PYTORCH_INDEX = "https://download.pytorch.org/whl/cu126/{name}/"
PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s]+)$")


class _Links(html.parser.HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attributes: list[tuple[str, str | None]]) -> None:
        if tag == "a":
            href = dict(attributes).get("href")
            if href:
                self.links.append(href)


def _request(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "A&D-Voice-lock-generator/1"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def _pypi_hashes(name: str, version: str) -> list[str]:
    document = json.loads(_request(PYPI_JSON.format(name=name, version=version)))
    return sorted({item["digests"]["sha256"] for item in document["urls"]})


def _pytorch_hashes(name: str, version: str) -> list[str]:
    parser = _Links()
    parser.feed(_request(PYTORCH_INDEX.format(name=name)).decode("utf-8"))
    normalized = version.replace("+", "%2B").casefold()
    hashes = set()
    for link in parser.links:
        decoded = urllib.parse.unquote(link).casefold()
        fragment = urllib.parse.urlsplit(link).fragment
        if normalized.replace("%2b", "+") in decoded and fragment.startswith("sha256="):
            hashes.add(fragment.removeprefix("sha256="))
    return sorted(hashes)


def pins() -> list[tuple[str, str]]:
    result = []
    for line in INPUT.read_text(encoding="utf-8").splitlines():
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        match = PIN.fullmatch(value)
        if not match:
            raise ValueError(f"Lock input must contain exact pins, got {value!r}")
        result.append(match.groups())
    return result


def render() -> str:
    lines = [
        "# Generated by scripts/generate_python_lock.py from requirements-lock.in.",
        "# Do not edit by hand; installs must use pip --require-hashes.",
        "--extra-index-url https://download.pytorch.org/whl/cu126",
        "",
    ]
    for name, version in pins():
        hashes = _pytorch_hashes(name, version) if "+cu126" in version else _pypi_hashes(name, version)
        if not hashes:
            raise RuntimeError(f"No published SHA-256 artifacts found for {name}=={version}")
        lines.append(f"{name}=={version} \\")
        lines.extend(
            f"    --hash=sha256:{digest}{' \\' if index + 1 < len(hashes) else ''}"
            for index, digest in enumerate(hashes)
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the verified Python dependency lock")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            print("requirements-lock.txt is stale; run scripts/generate_python_lock.py")
            return 1
        print(f"Verified {len(pins())} hash-locked Python packages")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(generated.encode()).hexdigest()
    print(f"Generated {OUTPUT.relative_to(ROOT)} ({len(pins())} packages, sha256:{digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
